export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_SELECTED_CATEGORY = "GET_SELECTED_CATEGORY";
export const SET_SELECTED_CATEGORY = "GET_SELECTED_CATEGORY";
