export const GET_CARTDATA_SUCCESS = "GET_CARTDATA_SUCCESS";
export const POST_CARTDATA_SUCCESS = "POST_CARTDATA_SUCCESS";

export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

export const GET_PRODUCT_FOR = "GET_PRODUCT_FOR";
export const SET_PRODUCT_FOR = "SET_PRODUCT_FOR";

export const SET_FILTER = "SET_FILTER";

//Admin

export const GET_REQUEST_ADMIN_SIDE = "GET_REQUEST_ADMIN_SIDE";
export const GET_FAILURE_ADMIN_SIDE = "GET_FAILURE_ADMIN_SIDE";


export const GET_SUCCESS_ADMIN_SIDE = "GET_SUCCESS_ADMIN_SIDE";
export const ADD_PROD_SUCCESS_ADMIN_SIDE = "ADD_PROD_SUCCESS_ADMIN_SIDE";
export const EDIT_PROD_SUCCESS_ADMIN_SIDE = "EDIT_PROD_SUCCESS_ADMIN_SIDE";
export const DELETE_PROD_SUCCESS_ADMIN_SIDE = "DELETE_PROD_SUCCESS_ADMIN_SIDE";

//get User Action Type

export const GET_SUCCESS_USER_DATA = "GET_SUCCESS_USER_DATA"




